#!/usr/bin/env python3

import sys
import os
import argparse

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("origlog", type=str, help="Original log file")
    ap.add_argument("newlog", type=str, help="New log file")
    args = ap.parse_args()

    with open(args.origlog, 'r', encoding='utf-8') as f:
        orig_warn = f.read().splitlines()

    with open(args.newlog, 'r', encoding='utf-8') as f:
        new_warn = f.read().splitlines()

    for line in new_warn:
        if not line.startswith('\t'):
           if not line in orig_warn:
               found = True
               print(line)
           else:
               found = False
        elif found:
            print(line)
